### ISSUE TITLE
Error to run test.py

### ISSUE THREAD

**Issue by menesesj** [ejokeeffe/tradedownloader#11]
Hi, when I run test.py from Spyder  I get the next error:

import scipy as sp
import getTradeDataFromComtrade

**comapi=getTradeDataFromComtrade.ComtradeApi()
df=comapi.getComtradeData(comcodes=['all'], reporter=['32'], partner=['all'],
                        years=[2016], freq='A', rg=['1'], fmt='json', rowmax=50000)
print(df.head)**

Traceback (most recent call last):

  File "<ipython-input-27-4c5108b1a52c>", line 4, in <module>
    comapi=getTradeDataFromComtrade.ComtradeApi()

  File "C:\Users\JMENESES2\OneDrive - United Nations\Python\tradedownloader\tradedownloader\getTradeDataFromComtrade.py", line 50, in __init__
    self._ctry_codes['End Valid Year'] > 2012]

  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\ops.py", line 1253, in wrapper
    res = na_op(values, other)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\ops.py", line 1140, in na_op
    result = _comp_method_OBJECT_ARRAY(op, x, y)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\ops.py", line 1119, in _comp_method_OBJECT_ARRAY
    result = libops.scalar_compare(x, y, op)

  File "pandas\_libs\ops.pyx", line 98, in pandas._libs.ops.scalar_compare

**TypeError: '>' not supported between instances of 'str' and 'int'**

**Javier**

Note: I am a novel in Python!!

**Comment by ejokeeffe** [comment]
Hi @menesesj, sorry it's taken me a while to get back, i've been away. Let me check this out and get back to you.

**Comment by menesesj** [comment]
I found that  .ix is obsolete and I replaced it by loc, but the function no work anyway...

**Comment by ejokeeffe** [comment]
Looks like it's a problem with your country codes file. Can you share it
here and ill test with it.

**Comment by menesesj** [comment]
[UN Comtrade Country List.xlsx](https://github.com/ejokeeffe/tradedownloader/files/2434717/UN.Comtrade.Country.List.xlsx)
that it!
